image: node:0.12

stages:
- before_install
- install
- test

before_install:
  stage: before_install
  script:
    - npm config set spin false
  
install:
  stage: install
  script:
    - sudo npm install bower
    - npm install ember-cli
    - npm install phantomjs-prebuilt
    - npm install
    - bower install --allow-root
  
test:
  stage: test
  script:
    - ember test


