image: node:0.12

stages:
- before_install
- install
- test

before_install:
  - npm config set spin false
  
install:
  - npm install -g bower
  - npm install -g ember-cli
  - npm install -g phantomjs-prebuilt
  - npm install
  - bower install --allow-root
  
test:
  script:
    - ember test


